/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ThoughtsRouteImport } from './routes/thoughts'
import { Route as QualificationsRouteImport } from './routes/qualifications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkLanguageSoftwareRouteImport } from './routes/work/language-software'
import { Route as WorkCryptographyRouteImport } from './routes/work/cryptography'
import { Route as WorkBlockchainRouteImport } from './routes/work/blockchain'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsRoute = ThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const QualificationsRoute = QualificationsRouteImport.update({
  id: '/qualifications',
  path: '/qualifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkLanguageSoftwareRoute = WorkLanguageSoftwareRouteImport.update({
  id: '/language-software',
  path: '/language-software',
  getParentRoute: () => WorkRoute,
} as any)
const WorkCryptographyRoute = WorkCryptographyRouteImport.update({
  id: '/cryptography',
  path: '/cryptography',
  getParentRoute: () => WorkRoute,
} as any)
const WorkBlockchainRoute = WorkBlockchainRouteImport.update({
  id: '/blockchain',
  path: '/blockchain',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/qualifications': typeof QualificationsRoute
  '/thoughts': typeof ThoughtsRoute
  '/work': typeof WorkRouteWithChildren
  '/work/blockchain': typeof WorkBlockchainRoute
  '/work/cryptography': typeof WorkCryptographyRoute
  '/work/language-software': typeof WorkLanguageSoftwareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/qualifications': typeof QualificationsRoute
  '/thoughts': typeof ThoughtsRoute
  '/work': typeof WorkRouteWithChildren
  '/work/blockchain': typeof WorkBlockchainRoute
  '/work/cryptography': typeof WorkCryptographyRoute
  '/work/language-software': typeof WorkLanguageSoftwareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/qualifications': typeof QualificationsRoute
  '/thoughts': typeof ThoughtsRoute
  '/work': typeof WorkRouteWithChildren
  '/work/blockchain': typeof WorkBlockchainRoute
  '/work/cryptography': typeof WorkCryptographyRoute
  '/work/language-software': typeof WorkLanguageSoftwareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/qualifications'
    | '/thoughts'
    | '/work'
    | '/work/blockchain'
    | '/work/cryptography'
    | '/work/language-software'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/qualifications'
    | '/thoughts'
    | '/work'
    | '/work/blockchain'
    | '/work/cryptography'
    | '/work/language-software'
  id:
    | '__root__'
    | '/'
    | '/qualifications'
    | '/thoughts'
    | '/work'
    | '/work/blockchain'
    | '/work/cryptography'
    | '/work/language-software'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QualificationsRoute: typeof QualificationsRoute
  ThoughtsRoute: typeof ThoughtsRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualifications': {
      id: '/qualifications'
      path: '/qualifications'
      fullPath: '/qualifications'
      preLoaderRoute: typeof QualificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/language-software': {
      id: '/work/language-software'
      path: '/language-software'
      fullPath: '/work/language-software'
      preLoaderRoute: typeof WorkLanguageSoftwareRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/cryptography': {
      id: '/work/cryptography'
      path: '/cryptography'
      fullPath: '/work/cryptography'
      preLoaderRoute: typeof WorkCryptographyRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/blockchain': {
      id: '/work/blockchain'
      path: '/blockchain'
      fullPath: '/work/blockchain'
      preLoaderRoute: typeof WorkBlockchainRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface WorkRouteChildren {
  WorkBlockchainRoute: typeof WorkBlockchainRoute
  WorkCryptographyRoute: typeof WorkCryptographyRoute
  WorkLanguageSoftwareRoute: typeof WorkLanguageSoftwareRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkBlockchainRoute: WorkBlockchainRoute,
  WorkCryptographyRoute: WorkCryptographyRoute,
  WorkLanguageSoftwareRoute: WorkLanguageSoftwareRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QualificationsRoute: QualificationsRoute,
  ThoughtsRoute: ThoughtsRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
